[package]
name = "wasm-ck3"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["miniz", "zstd/fat-lto"]
miniz = ["ck3save/miniz"]
libdeflate = ["ck3save/libdeflate"]

[dependencies]
jomini = "0.21"
schemas = { path = "../schemas" }
wasm-bindgen = { version = "0.2" }
serde-wasm-bindgen = "0.5"
serde = { version = "1", features = ["derive"] }
ck3save = { path = "/home/clemux/dev/ck3save" }
js-sys = "0.3"
zstd = { version = "0.12.3", default-features = false }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false